### PR TITLE
QGC does not send PROTO_GET_CHIP

### PR DESCRIPTION
**Pull request by davids5**
This fixes Error:Board erase failed error.

@LorenzMeier

### CODE REVIEW

**Comment by davids5** [comment]
Tested on Windows and  Ubuntu 19.10

**Comment by davids5** [comment]
@bkueng I did this back in 2015 to understand the protocol. 
[px4pipbl.pdf](https://github.com/PX4/Bootloader/files/3876827/px4pipbl.pdf)

**Comment by bkueng** [comment]
Cool, can we add this to the docs somewhere?
@hamishwillee fyi

**Comment by hamishwillee** [comment]
I assume that @davids5 is going to add it?

Not sure what to advise - depends on where the people who are mostly likely to want to use this would find it? If that is in this repo then I'd add it into a folder /docs with a readme explaining what it is for.

If this is more useful for a PX4 developer then you'd want it in http://dev.px4.io/master/en/hardware/ with a heading and line explaining what the file is for/how it is used.

**Pull request merged**
