### PR TITLE
add 'make format' and 'make check_format' to enforce astyle

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
The version of astyle available on travis doesn't have these options.
align-reference=name
ignore-exclude-errors-x
max-code-length=120

**Comment by dagar** [comment]
Different versions of astyle (like in ubuntu 12.04 vs 14.04) seem to contradict each other, so having travis  automatically check formatting isn't going to work.

**Comment by thomasgubler** [comment]
How bad is it? E.g. what example gives a conflict? Could we run multiple versions on travis and pass the commit if one of them returns ok?

**Comment by dagar** [comment]
https://travis-ci.org/PX4/Bootloader/builds/49543598

Between the travis version (ubuntu 12.04) of astyle and the one in ubuntu 14.04 this spacing was flipping back and forth.

-					c = 0xedb88320U ^ (c >> 1);
+					c = 0xedb88320U ^(c >> 1);

-		state = crctab[(state ^ src[i]) & 0xff] ^ (state >> 8);
+		state = crctab[(state ^ src[i]) & 0xff] ^(state >> 8);

**Comment by dagar** [comment]
clang-format might be a better option

**Comment by thomasgubler** [comment]
if we can configure it to give the exact same results as with astyle (at
least of the latest version) it might be worth a test

**Comment by dagar** [comment]
Due to the differences in astyle output and inability to get clang-format to match astyle I'll let this go for now.

**Pull request closed without merging**
