### PR TITLE
Added the ability to bootload from either the USB or the USART. Currently...

### PR DESCRIPTION
**Pull request by ksschwabe**
... this is compiled in only for the Px4FMU.

Please read through this whole message before accepting my pull request. I have had to comment out the #if BOOT_DELAY_ADDRESS section of code to make it work properly. Also, the current master branch of the bootloader has a problem and it will not boot to the app. I have fixed this and will explain this fix later. I will detail my changes in the message below.

As requested here is my attempt at a parallel USB and USART bootloader. As a quick overview, I have made the following changes.

- I have added a new interface to the Makefile (this is USART_USB).

- In the Makefile.f1 and Makefile.f4, it will compile in the usart.c and the cdcacm.c files.

- Since both the cdcam.c and the usart.c files use functions of the same name (cinit, cfini, cin and cout), I have had to change their names to cinit_usart and cinit_usb, etc.

- In the bl.c file I have now changed the bootloader function to accept both the timeout and the bootloader type (either USART or USB) . This option will then set the appropriate functions cin_usb or cin_usart and cout_usb or cout_usart to the function pointers cin and cout. Perhaps to make it a bit cleaner I should pass the function pointers as parameters to the bootloader. Otherwise, the basic logic of the bootloader is the same as before.

- I have also now given the bootloader an int return type. If it returns 0, it means an app has been uploaded successfully and you can try to boot. If it returns -1, it means that the bootloader has timed-out.

- In order to accommodate the ability to have parallel USB and USART bootload ability, I have had to add some more variables to the main_f4.c file. These are to tell you whether you should try to boot from the USB bootloader or the USART bootloader.

- (BUG FIX:) The current master branch of the bootloader, does not boot. it will boot if you upload an app via the USB, but if you just power on the board, it will not boot. This is owing to a change that was made in the cdcam.c file in February (I found this error today whilst trying to merge in my changes). In cdc_disconnect(void), the function usbd_disconnect(usbd_dev, true) is called. This is called in the cfini() in the cdcam.c file which is called in the jump_to_app() function. In the current logic, the usbd_dev variable is not defined until cinit is called. This is currently called only AFTER the if(try_boot) section of code. This means that when jump_to_app() function is called in the if(try_boot) section of code, the program gets stuck in some blocking call somewhere. To fix this I have moved the cinit() to before the if(try_boot) section.

- Also I have had to comment out the #ifdef BOOT_DELAY_ADDRESS section of code. It seems that this section of code currently sets my bootloader timeout_usb value to 0. This means that if the USB and the USART are connected and it tries to boot from the USB first it will never time out of the USB bootloader before trying the USART bootloader. My current logic is that if it is compiled for the USB and USART bootloader in parallel, and the boot signature is set, then it only sets the timeout of the USART bootloader to 0. The USB timout remains at its default value (see logic below). If the USB is not connected, it will not try the USB bootloader and go straight to the USART bootloader. If the USB cable is connected, it will timeout of the USB bootloader before trying the USART bootloader.

The basic flow of the main program is as follows.
- Enters main.
- If boot signature not set or the USB not connected, try to jump to the app immediately.
- If jumping to the app failed, try the USART bootloader forever.
- If the USB is connected, don't try to boot and try the USB bootloader. If timed-out, try to boot like usual.
- If the USB is disconnected and the boot signature is set, try the USART bootloader.
- If the USB is connected AND the boot signature is set, don't try to boot, then first try the USB bootloader. If you timeout try the USART bootloader. If an app was successfully uploaded by the USB bootloader, it will try to jump_to the_app. If that fails it will then try the USART bootloader.

Perhaps you guys have a more elegant way of dealing with the code where it tries the bootloaders, and depending on whether an app was successfully uploaded or not, try to boot or not.

- NOTE: I have only added the USART pin and RCC clock configurations for the PX4FMU board. Someone will need to add the USART pin configs for the the other boards. I don't have access to them, so I haven't been able to test them, and I didn't want to add the pin and clock configs here as if I knew that they worked.

COMPILING FOR USB_USART
To get the bootloader to compile for both the USB and USART, you will have to change the interface from USB to USART_USB in the makefile.

Please also note that I have only added the parallel bootloading logic to the main_f4.c file. main_f1.c is largely the same as before.

Sorry for the long message. I hope this made some sense.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks! @davids5 Could you have a look and comment?

**Comment by molyswu** [comment]
Thanks!

**Comment by davids5** [comment]
@ksschwabe , @LorenzMeier  This is on my radar. But there are som other bootloader related tasks that need to be completed birst and as stated in https://github.com/PX4/Bootloader/issues/27  these dual boot changes are substantial, we will need time to review them thoroughly. 

Thank you again for all your efforts!

**Comment by ksschwabe** [comment]
@davids5. No worries. I understand that it will take some time to go through my logic.

On a slightly related question, Lorenz mentioned that the bootloader might be getting some support for dropping bits and bytes when doing updates over the USART via a wireless link. Is this genuinely happening sometime "soon" or should I start looking into doing something myself for my own purposes? That being said, I would probably only get to that in about 3 weeks' time.

**Pull request closed without merging**
