### PR TITLE
[WIP] fmuk66

### PR DESCRIPTION
**Pull request by davids5**
1) Rename NXPhlite to FMUK66 and correct VID,PID
2) Fix Serial number and Name in descriptor

### CODE REVIEW

**Comment by jarivanewijk** [comment]
@davids5 - First of all, thank you for picking this up again. You're probably still testing/working on improvements, but I found that with the new changes the bootloader now takes about 30 seconds before it actually boots PX4. Also, firmware upgrade is still not working, I still get the same error as discussed in mavlink/qgroundcontrol#7360

**Comment by davids5** [comment]
@jarivanewijk - not done yet :) I fixed that issue, and cleaned up a bunch of CDC setttings that were wrong, but still no joy yet! I can see the smoking gun, not that the noise is cleared, but I have to see what I can do to fix it.

**Comment by davids5** [comment]
@jarivanewijk - Would you please test on both Windows and Linux.
@igalloway FYI

**Comment by jarivanewijk** [comment]
@davids5 - I was able to program firmware multiple times on both Windows 7 and Ubuntu 18.04 (virtual machine) through QGroundControl. Everything seems to work. Great job!

**Pull request merged**
