### PR TITLE
FMUv5 Move bootloader to telem2 @ 2mbps

### PR DESCRIPTION
**Pull request by davids5**
@DanielePettenuzzo @LorenzMeier I need this for testing uploader changes so here it is in a PR.

### CODE REVIEW

**Comment by mhkabir** [comment]
Can we use `bl_update` (https://github.com/PX4/Firmware/blob/master/src/systemcmds/bl_update/bl_update.c) to update the FMUv5 to this version of the bootloader?

**Comment by davids5** [comment]
@mhkabir - I would use a JTAG. The F7 has slightly different interface to flash then the F4 that the lb_update was written for.

**Comment by davids5** [comment]
@bkueng - 

Yes - It will require a little bit of work. It should be added to the list of projects. 

There is no F7 flash driver in NuttX and it will have developed and debugged, then upstreamed and back ported. The good news is deltas are obvious from the bootloader code.

**Comment by mhkabir** [comment]
Okay, we're in a production environment with multiple deployed units, so JTAG isn't an option. It would be good if `bl_update` can be fixed soon.

**Comment by dagar** [comment]
To be paranoid we could comment out bl_update from the F7 PX4 configs.

**Comment by dagar** [comment]
Great, that also works.

**Comment by mhkabir** [comment]
@dagar @davids5 can we merge this?

**Comment by mhkabir** [comment]
Superseded by https://github.com/PX4/Bootloader/pull/157

**Comment by davids5** [comment]
To close the loop here. bl_update was reved to support F7 and H7.

**Pull request closed without merging**
