### PR TITLE
WIP - Do not merge: Wireless bootloading

### PR DESCRIPTION
**Pull request by ksschwabe**
@LorenzMeier @davids5 
(Related to Issue #48)

This is the initial work that I have done on the wireless bootloading logic.

Changes:
 * BL revision increased to 6
 * PROG_MULTI protocol changed
   * Previously the protocol was PROG_MULTI/<len:1>/<data:len>/EOC, I have now changed it to PROG_MULTI/<begin_address:4>/<len:1>/<data:len>/<crc:4>/EOC
 * I need to send the address as well to say at what starting address this packet should be. This is because the response packet may not be received, in which case the same previous data packet would be sent and I need a way to ensure that that is written to the correct section of memory.
 * Added a flush to the bootloader RX buffer, so that if there is an error, (incorrect address, bad CRC, bad command) then the RX buffer is cleared for the next message that is sent.
 * Added two new failure response commands (BAD_ADDRESS and BAD_CRC). Admittedly I don't really use BAD_CRC for anything, so I could possibly remove that and just send a PROTO_INVALID response back to the uploader - please give me your input. 

I have put the px_uploader script with my changes into this PR for the moment so that you can pull and test without having to have another PR on PX4/Firmware. I will make a "sister" PR for the update of the uploader on PX4/Firmware when we are ready to merge this in.

Changes to px_uploader:
* The uploader will wait for a sync for a timeout period. If no response has been received, it will try to resend the PROG_MULTI data. 
 * If a "failed" or "invalid" response is received, it will resend the message
 * The uploader will try to program the data for up to 5 seconds. If it has not received a "successful" response, it will then timeout.

Problems:
 * The compilation is now 156 bytes too large for the standard PXIO bootloader. We will have to see what we can do to reduce the code or perhaps increase the allocated space for the PXIO bootloader.
 * Currently the response packets do not have a CRC. Therefore there is the possibility that a response packet gets mangled in the air and is received as a valid "successful" response, when it should have been an invalid response.
 * Currently only the programming of the flash message has a CRC. None of the other traffic has CRCs, so there is the potential for bad data to be received on both sides. Such as the the Serial number and chip description reporting back to the uploader. Thoughts?

I think the code definitely needs a bit more work, but I would like a bit of feedback from you guys to tell me what direction I should take this. Give it a try, first with the an FTDI cable and then perhaps with your wireless module. I have tested it with an FDTI cable simulating bit and byte drops and have also used a Laird RM024 wireless module.

What do you guys think?

### CODE REVIEW

**Comment by SimonWilks** [comment]
@ksschwabe I gave this a try today. I can confirm that in my case flashing via USB still works but I'm not able to flash via serial. Perhaps I'm missing something.

What I'm trying is using the 3DR (433MHz) telemetry modules on the pixhawk/laptop. I changed usart.c to work at 57600 instead of 115200 so I don't need to alter comms speeds elsewhere. To flash the firmware I then run the px_uploader.py script provided in this branch as follows:

python Tools/px_uploader.py --port /dev/ttyUSB0 --baud 57600 build_px4fmu-v2_default/src/firmware/nuttx/nuttx-px4fmu-v2-default.px4

The pixhawk is powered and reboots via mavlink are being triggered but nothing more than this happens. Essentially it just keeps rebooting. It doesn't seem to be receiving the initial sync message (INSYNC) it's expecting.

Any idea what might be wrong before I dig deeper?

**Comment by ksschwabe** [comment]
@SimonWilks : I don't know why that doesn't work. It has been a while since I looked at this code, and I can't remember off-hand what problem I had when setting it up initially. 

What I would suggest is trying it with an FTDI cable using a baud rate of 115200; then you shouldn't have any bit or byte drops so it should work just the same as with the USB.

It currently doesn't handle bit and byte drops in the sync packages, so if the uploader doesn't receive that initial sync and initial board information from the Px4, then I can imagine that it would fail.

**Comment by SimonWilks** [comment]
@ksschwabe good idea, I'll do that and then take a closer look and see if I can spot the issue. Thanks.

**Comment by AndreasAntener** [comment]
@SimonWilks @ksschwabe so, I was able to flash over two RFD868 :). The flashing took a few minutes though..

First issue, the reboot loop: I had it working via FTDI directly first, and then I suddenly got into the reboot cycle like Simon did. The reason was that I switched from USB to PSM power. It has to be powered via USB, otherwise it doesn't go (probably obvious for the BL experts :8)

Second issue, timeout: with FTDI it worked without problems, but with the RFD radio I got the timeout after erasing. First I reduced the `PROG_MULTI_MAX` to 128 which helped and it started to transmit and acknowledge data. After a bit of thinking I then set it back to 252 but disabled MAVLink framing on the RFD radios, which then also worked.

So my working setup is:
- all baudrates to 115200 (needs custom mavlink start on pixhawk)
- power via USB
- relevant RFD config
S1:SERIAL_SPEED=115
S2:AIR_SPEED=128
S6:MAVLINK=0

**Comment by ksschwabe** [comment]
@AndreasAntener : When the board is powered on and it detects 5V on the USB it goes into the 5s wait in the BL, where it waits for some BL messages. If it timesout after 5s it boots normally. If it starts without power on the USB, you can still get it to go into the BL if you pull the RX line of the UART port that it uses to communicate low. This can be accomplished by either manually pulling it low when starting, or by continuously sending a "BREAK" command over the UART. I know the "BREAK" command does work when I've tested sending it over an FTDI cable, and I also manged to get it to work with an RM024 Laird wireless module. You will have to see how break command is sent over the wireless modules that you are using.

Have a look with a Logic analyser or an oscilloscope if you have one.

With the timeout on erasing, I think the problem might be that the code isn't properly handling the resending of the "SYNC" packets at the end of the erase. So if one gets lost, I think you have to start again.

**Comment by AndreasAntener** [comment]
Continued here: https://github.com/PX4/Bootloader/pull/61

**Pull request closed without merging**
